### ISSUE TITLE
faileed

### ISSUE THREAD

**Issue by Fromthebottom** [animemoeus/telegram-bot#111]
"Hey there! I hope you're doing well. I wanted to give you a heads up that it seems like our Telegram bot has hit a bit of a snag and stopped working. I'm not quite sure what's causing the issue, but I thought it's best to keep you in the loop.

Let's brainstorm some alternatives or explore if there's a fix for this. I'm sure we can find a solution together. Looking forward to catching up soon and sorting this out. Take care!"

**Comment by animemoeus** [comment]
Hellow o(*￣▽￣*)ブ

Can you explain more detail about the problem?

Like, in which bot the problem happens, how to replicate the problem, etc?

Coz there is no error in my sentry report, hahaha.
![image](https://github.com/animemoeus/telegram-bot/assets/33395829/db29c3ab-f634-4c7f-9fff-c9ca06a53187)
